### PR TITLE
Added element orientation

### PR DESCRIPTION
**Pull request by akturner**
**Summary**

Adds a calculation of the element orientation to nve/sphere fix. Added orientation and moment of inertia variables to the DEMSI model. 

DEMSI concomitant PR: https://github.com/E3SM-Project/DEMSI/pull/302

**Related Issues**

Fixed some minor formatting issues.

**Author(s)**

Adrian K. Turner (akt@lanl.gov)

### CODE REVIEW

**Comment by snikolov3** [comment]
I tried running the uniform_stress test case with openmp in debug mode and I was getting division by zero in several places. Not sure if this is the intended behavior. Some of these locations are listed below:

fix_nve_sphere_demsi.cpp:134
fix_nve_sphere_demsi.cpp:197
pair_gran_hopkins_kokkos.cpp:752
pair_gran_hopkins_kokkos.cpp:412
pair_gran_hopkins_kokkos.cpp:445
pair_gran_hopkins_kokkos.cpp:447
pair_gran_hopkins_kokkos.cpp:454

Should we also initialize dtirotate and dtfrotate to some value?

I seem to run into segmentation faults on the 14th tilmestep. I seem to be getting nans for the orientation[i] and omega[][] arrays.

Breakpoint 9, LAMMPS_NS::FixNVESphereDemsi::initial_integrate (this=0xab80002a780)
    at /ascldap/users/snikolo/Orientation/DEMSI/model/LAMMPS/src/USER-DEMSI/fix_nve_sphere_demsi.cpp:137
137	      orientation[i] += dtv * omega[i][2];
(gdb) p omega[i][2]
$79 = nan(0x8000000000000)
(gdb) p orientation[i]
$80 = nan(0x8000000000000)

**Review by snikolov3 — COMMENTED** [review]
I tried running the uniform_stress test case with openmp in debug mode and I was getting division by zero in several places. Not sure if this is the intended behavior. Some of these locations are listed below:

fix_nve_sphere_demsi.cpp:134
fix_nve_sphere_demsi.cpp:197
pair_gran_hopkins_kokkos.cpp:752
pair_gran_hopkins_kokkos.cpp:412
pair_gran_hopkins_kokkos.cpp:445
pair_gran_hopkins_kokkos.cpp:447
pair_gran_hopkins_kokkos.cpp:454

Should we also initialize dtirotate and dtfrotate to some value?

I seem to run into segmentation faults on the 14th tilmestep. I seem to be getting nans for the orientation[i] and omega[][] and force[][] arrays. The nans in the force array propagate to orientation and omega and the velocities also. I copied this DEMSI directory and switched to the master version of DEMSI-LAMMPS instead of the the element_orientation branch and the issue was not occurring.

Breakpoint 9, LAMMPS_NS::FixNVESphereDemsi::initial_integrate (this=0xab80002a780)
at /ascldap/users/snikolo/Orientation/DEMSI/model/LAMMPS/src/USER-DEMSI/fix_nve_sphere_demsi.cpp:137
137 orientation[i] += dtv * omega[i][2];
(gdb) p omega[i][2]
$79 = nan(0x8000000000000)
(gdb) p orientation[i]
$80 = nan(0x8000000000000)

**Comment by akturner** [comment]
@snikolov3 @karapeterson I've added the concomitant DEMSI PR to the PR message above.

**Comment by akturner** [comment]
@snikolov3 @karapeterson: Anyone managed to look at this yet?

**Comment by karapeterson** [comment]
@akturner - changes look good in LAMMPS. With the associated DEMSI changes, the code builds and runs.  One minor issue, the polygon unit test fails for me on the polygon intersection test.

**Comment by akturner** [comment]
@karapeterson That failure is expected. There are some redundant vertices generated sometimes that don't affect the simulation but should be fixed at some point.

**Pull request merged**
