### PR TITLE
Added ice concentration dependency to the Hopkins contact model

### PR DESCRIPTION
**Pull request by akturner**
Added Hibler exponential ice concentration dependency of plastic resistance to Hopkins contact model
Added ice concentration variable passed from DEMSI
Add new parameter for Hibler dependency
Moved several parameters to pair interface

**Summary**

This adds a Hibler like dependency on the plastic friction with an exponential dependency on ice concentration. Low concentration ice shows very low resistance to convergence.

**Related Issues**

None

**Author(s)**

Adrian K. Turner, LANL

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Several new inputs added to the pair hopkins contact model

### CODE REVIEW

**Comment by akturner** [comment]
Goes with this DEMSI branch: https://github.com/akturner/DEMSI/tree/lammps_ice_concentration

**Review by snikolov3 — COMMENTED** [review]
Everything compiles for me. The variable declaration/definitions you have look good. Will the ice_concentration be stored for each bond? If that is the case

PairGranHopkins::PairGranHopkins(LAMMPS *lmp) :
              PairGranHookeHistory(lmp, 12)

may need to change to 

PairGranHopkins::PairGranHopkins(LAMMPS *lmp) :
              PairGranHookeHistory(lmp, 13)

i.e. changing _size_history in pair_gran_hooke_history.cpp

-Svetoslav

**Comment by akturner** [comment]
@snikolov3 IceConcentration is only stored per particle not per bond.

**Review by karapeterson — APPROVED** [review]
Changes look good to me and everything builds and runs fine.

**Pull request merged**
